# AUTOGENERATED FROM 'app/fastui/queries/check_user_deletable.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import edgedb


async def check_user_deletable(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
) -> bool:
    return await executor.query_single(
        """\
        with user:= assert_single((select User{events:= .<host[is Event]} filter .name=<str>$name)),
        select not exists user.events;\
        """,
        name=name,
    )
