# AUTOGENERATED FROM 'app/queries/ping_db.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import edgedb


async def ping_db(
    executor: edgedb.AsyncIOExecutor,
) -> int:
    return await executor.query_single(
        """\
        select 1;\
        """,
    )
