# AUTOGENERATED FROM 'app/queries/update_event.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateEventResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    address: str | None
    schedule: datetime.datetime | None
    host_name: str


async def update_event(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
    new_name: str | None,
    address: str | None,
    schedule: str | None,
    host_name: str | None,
) -> UpdateEventResult | None:
    return await executor.query_single(
        """\
        with name := <str>$name,
             orig_event := assert_exists(assert_single((select Event filter .name=name))),
             orig_event_name:= orig_event.name,
             orig_event_address:= orig_event.address,
             orig_event_schedule:= orig_event.schedule,
             orig_event_host_name:= orig_event.host.name,
             new_name := <optional str>$new_name ?? orig_event_name,
             address := <optional str>$address ?? orig_event_address,
             schedule := <datetime>(<optional str>$schedule) ?? orig_event_schedule,
             host_name := <optional str>$host_name ?? orig_event_host_name,
        select (
            update Event filter .name = name
            set {
                name := new_name,
                address := address,
                schedule := schedule,
                host := (
                    with u:= assert_single((select detached User filter .name = host_name)),
                    select 
                    if exists u then (u)
                    else (insert User {name:= host_name})
                )
            }
        ) {name, address, schedule, host_name:=.host.name};\
        """,
        name=name,
        new_name=new_name,
        address=address,
        schedule=schedule,
        host_name=host_name,
    )
